name: Build and Test

on:
  push:
    branches:
      - main
      - 1.x
  pull_request:
    branches:
      - main
      - 1.x

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Test
        run: npm run test

      - name: Archive test artifacst
        uses: actions/upload-artifact@v4
        with:
          name: test images
          path: |
            test/e2e/**/*.png


  license:
    runs-on: ubuntu-latest

    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Fossa and upload data
        if: env.FOSSA_API_KEY != ''
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ env.FOSSA_API_KEY }}
